---
- hosts: localhost
  tasks:
  - name: Get stats of the FS object
    ansible.builtin.stat:
      path: /tmp
    register: output_stat

  - name: Print a debug message
    ansible.builtin.debug:
      msg: "Path /tmp exist"
    when: output_stat.stat.islnk is defined
  
  - include_role:
      name: my_role
